package org.maktab.entity;

public enum OrderStatus {

    WAITING_FOR_PROFICIENT_OFFER,
    WAITING_FOR_PROFICIENT_SELECTION,
    WAITING_FOR_PROFICIENT_COMING,
    STARTED,
    FINISHED,
    PAYED
}
